#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SEG 0x08
#define KERNEL_DATA_SEG 0x10
#define USER_DATA_SEG   0x23
#define USER_CODE_SEG   0x1B

#define ENKI_SECTOR_SIZE         512
#define ENKI_TOTAL_INTERRUPTS    512
#define ENKI_TOTAL_GDT_SEGMENTS  6
#define ENKI_MAX_ISR_80H_CMD     1024

#define ENKI_HEAP_ADDRESS       0x01000000
#define ENKI_HEAP_TABLE_ADDRESS 0x00007E00
#define ENKI_HEAP_SIZE_BYTES    1024*1024*100  // 100 MB
#define ENKI_HEAP_BLOCK_SIZE    4096

#define ENKI_MAX_FILE_SYSTEMS     12
#define ENKI_MAX_FILE_DESCRIPTORS 512

#define ENKI_MAX_PATH            108
#define ENKI_MAX_PGM_ALLOCATIONS 1024
#define ENKI_MAX_PROCESSES       12

#define ENKI_USER_PGM_STACK_SIZE       1024 * 16
#define ENKI_PGM_VIRT_ADDR             0x400000
#define ENKI_PGM_VIRT_STACK_ADDR_START 0x3FF000
#define ENKI_PGM_VIRT_STACK_ADDR_END   ENKI_PGM_VIRT_STACK_ADDR_START - ENKI_USER_PGM_STACK_SIZE

#define ENKI_KEYBOARD_BUFFER_SIZE 1024

#endif